repos/iiif-storage/config/service.config.php, repos/iiif-storage/src/Link/CollectionLink.php, repos/iiif-storage/src/Link/ManifestLink.php, repos/iiif-storage/view/iiif-storage/link/collection.phtml, repos/iiif-storage/view/iiif-storage/link/manifest.phtml
Allows you to choose a manifest or a collection, give it a label
and have it show up in the menu, without having to hard-code in
the current site ID or the slug for the manifest or collection.
=> Manifest and Collection in site navigation as options

repos/omeka-i18n-module/Module.php, repos/omeka-i18n-module/src/Form/LocalizationConfigForm.php, repos/omeka-i18n-module/src/Translator/DelegateTranslatorFactory.php
Split the configuration form into 2 options:
* Enable Localisation
* Enable Transifex
Also split the feature flags into 2, few updates to use the base config form for consistency thrown in too. Also commented out some dead code (according to Intelij)
=> Removed Transifex as dependency for localisation

CHANGELOG.md, repos/annotation-studio/Module.php, repos/annotation-studio/src/AnnotationStudioFactory.php, repos/annotation-studio/src/CaptureModel/CaptureModelRepository.php, repos/annotation-studio/src/Components/CorePlugin.php, repos/annotation-studio/src/OmekaItemExpander.php, repos/omeka-i18n-module/config/controllers.config.php, repos/omeka-i18n-module/src/Controller/TranslationSyncController.php, repos/omeka-i18n-module/view/admin/i18n-synchronize/show.twig, repos/shared-library/src/Utility/OmekaValue.php, translations/madoc/template.pot
- Capture models can now be translated inside of Omeka and will correctly be served depending on your locale (closes #72)
- Fixed bug where you could sync without Transfiex enabled
- Fixed bug where locale was not being passed to annotation studio (closes #74)
=> Capture model translate

.travis/pre-release.sh, CHANGELOG.md
Local tool (for now) to build pre-release docker tags, without creating a latest tag to be manually pushed to Dockerhub.
=> Pre-release build

.gitignore, CHANGELOG.md, bin/theme-builder
The theme builder will create a zip file of all of the `twig` and `.phtml` templates used in the project. The directory structure is important, but you can take a single file and put it into the same directory path in a custom theme to get up and running quickly.
You could also grab the entire theme and overwrite everything, but this will cause problems if the underlying templates update. A possible addition could be a diff-tool to check changes against an updated madoc. 
To run the tool:
```
bin/theme-builder
```
this create a `theme.zip` containing all of the theme files. You can unzip this and find the view folder which corresponds to a theme's view folder.
=> Added theme builder

CHANGELOG.md, repos/public-user/Module.php
This is a temporary fix. The issue is the case-sensitivity of the `Transcriber` role. This is an issue standing since before the open-source release. When creating or editing a user in the backend, the variation that is used is `Transcriber`, so this standardises on that. If you are having issues you can simply update the role from the backend.
Future steps:
* Change to case-insensitive version
* Write migration tool to change `Transcriber` to `transcriber`
=> Transcriber role (case-sensitive)

CHANGELOG.md, repos/omeka-i18n-module/src/Site/LocalizationListener.php
- Fixes translations (incorrect `domain` value) which was working for the default site
- Adds `CHANGELOG.md` backlog
=> Translations fix

CHANGELOG.md, repos/annotation-studio/Module.php, repos/annotation-studio/src/CaptureModel/CaptureModelRepository.php, repos/annotation-studio/src/CaptureModel/Router.php, repos/annotation-studio/src/Controller/CaptureModelController.php
This stops capture models with `/en/` and `/cy/` being served.
=> Fixed bug when saving annotations from i18n site

infrastructure/terraform/madoc/single-instance/ec2.tf, infrastructure/terraform/madoc/single-instance/variables.tf
By default TF sets root as 8GiB which doesn't leave much room.
=> Make root ebs size configurable via variable, default 30GiB

services/madoc-ts/src/database/queries/resource-queries.ts, services/madoc-ts/src/gateway/api.ts, services/madoc-ts/src/router.ts, services/madoc-ts/src/routes/iiif/canvases/get-canvas-manifests.ts, services/madoc-ts/src/routes/iiif/manifests/get-manifest-collections.ts, services/madoc-ts/src/routes/projects/create-resource-claim.ts
When creating a resource claim, it will now try to fill in the blanks to ensure a consistent structure in the crowdsourcing task structure. If it's a canvas without a manifest or collection it will first look up all of the manifests that the canvas is in (in the same project) and if there's only one, it will use that. The same process for collections. This ensures that 99% of the time there is only one set of crowdsourcing tasks created in the UI.
2 new endpoints to enable this.
**Get manifests collections**
```
GET /api/madoc/iiif/manifests/123/collections
{
"collections": [123, 456]
}
```
**Get canvas manifests**
```
GET /api/madoc/iiif/canvases/123/manifests
{
"manifests": [123, 456]
}
```
=> Updated resource claims

docker-compose.madoc.yml
Tiny thing, keeps it consistent with mysql and allows the backup process to run.
=> Expose postgres port for shared instance

.env, docker-compose.yml, services/madoc-ts/src/gateway/api.ts, services/madoc-ts/src/router.ts, services/madoc-ts/src/routes/iiif/manifests/export-manifest.ts, services/madoc-ts/src/routes/iiif/manifests/search-manifest.ts, services/madoc-ts/src/types/schemas/search.ts
First implementation with limitations:
- Search across whole site, not per project
- Search is limited to test fields with box selectors
- Will only search approved items
- Output manifests do not support changes made after import - will patch the original manifest
=> Mirador / UV Search for annotations

docker-compose.yml, services/madoc-ts/package.json, services/madoc-ts/src/extensions/capture-models/DynamicDataSources/DynamicDataSources.extension.ts, services/madoc-ts/src/extensions/capture-models/DynamicDataSources/README.md, services/madoc-ts/src/extensions/capture-models/DynamicDataSources/sources/Plaintext.source.ts, services/madoc-ts/src/extensions/capture-models/DynamicDataSources/types.ts, services/madoc-ts/src/extensions/capture-models/Paragraphs/Paragraphs.extension.ts, services/madoc-ts/src/frontend/admin/molecules/CollapsibleTaskList.tsx, services/madoc-ts/src/frontend/admin/molecules/SortedTaskList.tsx, services/madoc-ts/src/frontend/admin/pages/content/canvases/edit-canvas-linking.tsx, services/madoc-ts/src/frontend/admin/pages/content/manifests/manifest.tsx, services/madoc-ts/src/frontend/admin/pages/crowdsourcing/model-editor/full-document-editor.tsx, services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/project-content.tsx, services/madoc-ts/src/frontend/admin/pages/enrichment/ocr.tsx, services/madoc-ts/src/frontend/admin/pages/enrichment/ocr/ocr-list.tsx, services/madoc-ts/src/frontend/admin/pages/enrichment/ocr/ocr-manifest.tsx, services/madoc-ts/src/frontend/admin/pages/tasks/generic-task.tsx, services/madoc-ts/src/frontend/admin/routes.tsx, services/madoc-ts/src/frontend/shared/atoms/Breadcrumbs.tsx, services/madoc-ts/src/gateway/api.ts, services/madoc-ts/src/gateway/fetch-json.ts, services/madoc-ts/src/gateway/tasks/process-canvas-ocr.ts, services/madoc-ts/src/gateway/tasks/process-manifest-ocr.ts, services/madoc-ts/src/routes/iiif/linking/convert-linking.ts, services/madoc-ts/yarn.lock, services/storage-api/src/utility/typed-router.ts
Adds the ability to import and edit plaintext OCR from seeAlso properties on IIIF resources.
1. Automatically fetches and imports plaintext OCR during import
2. Adds a new "data source" concept to capture models
3. Allows capture models to be configured to use the plaintext seeAlso property to pre-populate a field
This extension allows dynamic data sources to be defined and loaded when a capture model is created.
When a capture model is cloned, the following will happen:
- Detect if any of the fields in the capture model have data sources defined
- Load related code for generating data source, passing in the current resource and API
- Request the new value from the dynamic data source
- Return the model
This might not be in the scope of this but when data is saved (revision approved) then …
=> MAD-428 Plaintext OCR

services/madoc-ts/src/extensions/capture-models/Paragraphs/Paragraphs.helpers.ts, services/madoc-ts/src/frontend/admin/pages/content/canvases/canvas-plaintext.tsx, services/madoc-ts/src/frontend/admin/pages/content/canvases/canvas-search-index.tsx, services/madoc-ts/src/frontend/admin/pages/content/canvases/canvas.tsx, services/madoc-ts/src/frontend/admin/routes.tsx, services/madoc-ts/src/frontend/shared/components/CanvasNavigation.tsx, services/madoc-ts/src/frontend/site/pages/loaders/canvas-loader.tsx, services/madoc-ts/src/frontend/site/pages/view-canvas.tsx, services/madoc-ts/src/gateway/api.ts, services/madoc-ts/src/gateway/tasks/process-manifest-ocr.ts, services/madoc-ts/src/router.ts, services/madoc-ts/src/routes/iiif/canvases/get-canvas-plaintext.ts, services/madoc-ts/src/routes/site/site-canvas.ts, services/madoc-ts/src/types/schemas/canvas-full.ts, services/madoc-ts/src/utility/linking-property-types.ts
This will resolve the transcription from one of four places:
* Capture model data source (text plain) - newly added today
* Published capture model paragraphs - from OCR transformation
* Plaintext `seeAlso` linking property, but only if it has been stored in Madoc
* Intermediate paragraphs format in the `seeAlso`
There is a backend API for getting this data and also links into the frontend for loading canvases. Caching needs revisited on this.
=> MAD-133 - viewing transcription

docker-compose.yml, services/madoc-ts/package.json, services/madoc-ts/src/router.ts, services/madoc-ts/yarn.lock, services/storage-api/package.json, services/storage-api/src/app.ts, services/storage-api/src/config.ts, services/storage-api/src/router.ts, services/storage-api/src/routes/iiif/level-0.ts, services/storage-api/src/types.ts, services/storage-api/yarn.lock
* Upload public image to file service `/public/storage/[site-urn]/[bucket]/public/[path-to-image].jpg`
* Navigate to `/public/storage/iiif/0/[site-urn]/[bucket]/public/[path-to-image].jpg/info.json` (note: `/iiif/0` and `/info.json` additions)
* New route on the storage API: `/public/storage/iiif/0/[site-urn]/[bucket]/public/[path-to-image].jpg/info.json`
* When IIIF image is requested the first time, a zip file is created containing a level 0 image service folder structure
* file pointer to zip is held in memory for a short period hopefully for duration of tile loading cycles
* IIIF paths e.g. `/info.json` or `/2304,512,256,256/256,/0/default.jpg` are streamed from zip efficiently from disk
* info.json and tiled image requests are returned back to browser
=> Added built-in level-0 image service to IIIF Storage API

services/madoc-ts/src/database/queries/get-collection-snippets.ts, services/madoc-ts/src/database/queries/get-manifest-snippets.ts
Or more broadly, prevent collections being requested at manifest endpoints. Also makes sure no invalid types can be returned in a manifest (only canvases)
=> Prevent collections being indexed in search

services/madoc-ts/migrations/2021-05-25T14-24.change-discovery.sql, services/madoc-ts/migrations/down/2021-05-25T14-24.change-discovery.sql, services/madoc-ts/src/activity-streams/change-discovery-repository.ts, services/madoc-ts/src/activity-streams/change-discovery-types.ts, services/madoc-ts/src/activity-streams/router.ts, services/madoc-ts/src/activity-streams/routes/get-activity-stream-page.ts, services/madoc-ts/src/activity-streams/routes/get-activity-stream.ts, services/madoc-ts/src/activity-streams/routes/post-activity.ts, services/madoc-ts/src/frontend/admin/server.tsx, services/madoc-ts/src/frontend/site/server.ts, services/madoc-ts/src/gateway/api.server.ts, services/madoc-ts/src/middleware/postgres-connection.ts, services/madoc-ts/src/router.ts, services/madoc-ts/src/routes/iiif/manifests/build-manifest.ts, services/madoc-ts/src/routes/iiif/manifests/export-manifest.ts, services/madoc-ts/src/routes/iiif/manifests/search-manifest.ts, services/madoc-ts/src/routes/site/site-published-models.ts, services/madoc-ts/src/types/application-context.ts, services/madoc-ts/src/utility/postgres-tags.ts, services/madoc-ts/src/utility/slonik-helpers.ts
This PR contains the data model for managing generic activity streams. It provides a protocol for retrieving collections and pages as defined in the change discovery and a bespoke post endpoint for creating events.
Each stream can be sub-divided (or aggregated depending on how you look at it) into many streams.
The top level streams are one-to-one with sites in Madoc. The identifier of the stream is the URL you choose to POST activity too. This allows Madoc, or any system, to have ownership of where streams are. Madoc will use this to publish activity streams for projects and being able to construct that URL with a project identifier alone. 
As per the spec, when you fetch a stream it will look like this:
```json
GET /api/madoc/activity/test-stream/changes
{
"@context": …
```
=> MUYA-148 Activity streams

e2e/cypress/integration/crowdsourcing/04-transcriber-mode.ts, e2e/cypress/integration/crowdsourcing/05-selectors.ts, e2e/package.json, e2e/yarn.lock, services/madoc-ts/package.json, services/madoc-ts/src/frontend/shared/caputre-models/NewEntityInstanceButton.tsx, services/madoc-ts/src/frontend/shared/caputre-models/NewFieldInstanceButton.tsx, services/madoc-ts/src/frontend/shared/caputre-models/new/components/DefaultManagePropertiesList.tsx, services/madoc-ts/src/frontend/shared/caputre-models/new/components/DefaultSubmitButton.tsx, services/madoc-ts/src/frontend/shared/components/TaskItem.tsx, services/madoc-ts/src/frontend/site/features/ProjectCollections.tsx, services/madoc-ts/src/frontend/site/hooks/use-manifest-task.ts, services/madoc-ts/src/frontend/site/hooks/use-project-manifest-tasks.ts, services/madoc-ts/src/frontend/site/hooks/use-project-manifests.ts, services/madoc-ts/src/frontend/site/pages/all-tasks.tsx, services/madoc-ts/src/frontend/site/pages/view-manifest.tsx, services/madoc-ts/themes/.gitignore, services/madoc-ts/translations/en/madoc.json, services/madoc-ts/yarn.lock
Implements and tests [these](https://github.com/digirati-co-uk/capture-models/compare/78edea28b7df8451c4352565b0457c7bdf395fa8...master) changes to capture models.
First change was not correctly finding selectors that had been overwritten.
```diff
- current = (property as []).find((field: any) => field.id === id) as any;      
+ current = (property as []).find((field: any) => field.id === id || field.revises === id) as any;
```
The second change ensures the `revisedBy` field is cleared when cloning an entity.
```diff
if (clonedRestOfEntity.selector) {    
clonedRestOfEntity.selector.id = generateId();    
clonedRestOfEntity.selector.state = null;    
+ if (clonedRestOfEntity.selector.revisedBy) {      
+    delete clonedRestOfEntity.selector.revisedBy;    
+  }  
}
```
Covered with new …
=> MAD-770 - selectors + entity bugfixes

services/madoc-ts/src/extensions/capture-models/ConfigInjection/ConfigInjection.extension.ts, services/madoc-ts/src/extensions/capture-models/ConfigInjection/constants.ts, services/madoc-ts/src/extensions/capture-models/ConfigInjection/types.ts, services/madoc-ts/src/extensions/extension-manager.ts, services/madoc-ts/src/frontend/site/features/CanvasSimpleEditor.tsx, services/madoc-ts/src/gateway/api.ts, services/madoc-ts/src/router.ts, services/madoc-ts/src/routes/admin/get-model-configuration.ts, services/madoc-ts/src/routes/admin/update-model-configuration.ts, services/madoc-ts/src/routes/projects/list-projects.ts, services/madoc-ts/src/routes/site/site-model-configuration.ts, services/madoc-ts/src/routes/site/site-projects.ts, services/madoc-ts/test-utility/api-mock.ts
Just before the model is created (same step OCR is created) it will check the config server for objects that look like this:
```
{
"documentChanges": [
{
"property": "verses",
"field": "dataSource",
"value": "https://gist.githubusercontent.com/stephenwf/[ ... ]/completions-custom.json"
}
]
}
```
Which effectively translates to:
```
captureModel.document.properties.verses[0].dataSource = 'https://gist[...]/completions-custom.json'
```
Only works on top level capture model fields, and there’s a blacklist so this can’t ruin models. If it’s invalid, it just skips it. Config server let’s us configure it at any level, but I’ve limited it to only manifests. So you can say “Change this field in this capture model on all of the images in this manifest, in this project”
=> MUYA-149 - capture model config server overrides

CHANGELOG.md, services/madoc-ts/src/frontend/shared/components/MetaDataDisplay.tsx, services/madoc-ts/src/repository/site-user-repository.ts, services/madoc-ts/src/routes/admin/localisation.ts, services/madoc-ts/src/routes/iiif/collections/delete-collection.ts
- Fixed bug with `null` metadata values breaking admin
- Prevent error when deleting collection (task related)
- Fixed bug with invalid i18n configuration
- Fixed bug with missing sites when reducing statistics
=> 2.0.2 fixes

CHANGELOG.md, services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultPostSubmission.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/EditorSlots.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/SubmitWithoutPreview.tsx, services/madoc-ts/src/frontend/shared/configuration/site-config.ts, services/madoc-ts/src/frontend/site/features/CanvasSimpleEditor.tsx, services/madoc-ts/src/types/schemas/project-configuration.ts, services/madoc-ts/translations/en/madoc.json
Makes save buttons inline on the page:
Submit will submit for review directly, before showing the "Post submission" screen
Also compatible with #534
=> MAD-1091 Added new "Disable preview popup" project configuration option

CHANGELOG.md, services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultSubmitButton.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/EditorSlots.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/SubmitWithoutPreview.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/hooks/use-can-submit.ts
Added "canSubmit" which will disable the Submit button if required selectors are not complete. This will operate on two selectors
* Top level entity selectors
* Top level field selectors
This works if you have `allowMultiple=true` so if you set your capture model field to required you should ensure you understand how this will affect users filling in your model. It does **not**  work with selectors nested further than the top level.
It _should_ work with modelRoot changes, as this changes the document in the revision, if not that will be fixed.
=> MAD-1092 - Disable submit button

CHANGELOG.md, services/madoc-ts/src/frontend/shared/atoms/Images.tsx, services/madoc-ts/src/frontend/shared/capture-models/DocumentPreview.tsx, services/madoc-ts/src/frontend/shared/capture-models/editor/atoms/Grid.tsx, services/madoc-ts/src/frontend/shared/capture-models/editor/components/ChooseFieldButton/ChooseFieldButton.tsx, services/madoc-ts/src/frontend/shared/capture-models/editor/components/ChooseSelectorButton/ChooseSelectorButton.tsx, services/madoc-ts/src/frontend/shared/capture-models/editor/selector-types/BoxSelector/BoxSelector.tsx, services/madoc-ts/src/frontend/shared/capture-models/editor/stores/selectors/selector-hooks.ts, services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultBreadcrumbs.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultInlineEntity.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultManagePropertiesList.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/components/RevisionProviderWithFeatures.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/features/AutoSelectDefineRegion.tsx, services/madoc-ts/src/frontend/shared/capture-models/new/features/AutosaveRevision.tsx, services/madoc-ts/src/frontend/shared/capture-models/plugin-api/hooks/use-selector.ts, services/madoc-ts/src/frontend/shared/capture-models/plugin-api/hooks/use-selectors.ts, services/madoc-ts/translations/en/madoc.json
- Fixed default selected field "type" - it is now "text-field" making models quicker to create
- Fixed issue where you could not de-select an entity selector
- Fixed auto-selecting the "define" region when using editing an existing region
- Added "tiny" variation of image wrapper [dev]
- Added preview for entity lists using selector if it's available
- Added "confirm" to deselect or confirm the current selector
- Removed auto-save by default, causing errors and no immediate feedback to the user
=> MAD-1097 Various fixes

services/madoc-ts/src/frontend/shared/capture-models/_components/ViewDocument/render/render-property.tsx, services/madoc-ts/src/frontend/site/features/CreateModelTestCase.tsx, services/madoc-ts/stories/capture-models/interactions/CaptureModelTestHarness.tsx
changed` highlightRevisionChanges={revision}` to `filterRevisions={incompleteRevisions}` for the document tab
then made sure it filtered that out in `render-proterty`  before `filter-revise` becasue filter revise will return the most recent revision even if its not approved.
=> document view shows correct fields

CHANGELOG.md, services/madoc-ts/src/app.ts, services/madoc-ts/src/extensions/completions/extension.ts, services/madoc-ts/src/extensions/completions/sources/wikidata-source.ts, services/madoc-ts/src/extensions/completions/sources/worldcat-fast-source.ts, services/madoc-ts/src/extensions/completions/types.ts, services/madoc-ts/src/frontend/shared/capture-models/editor/input-types/AutocompleteField/AutocompleteField.tsx, services/madoc-ts/src/router.ts, services/madoc-ts/src/routes/site/site-completions.ts, services/madoc-ts/src/types/application-context.ts
Migrated from:
https://github.com/digirati-co-uk/madoc-platform/blob/1.2.17/repos/auto-complete/src/Controller/CompletionController.php#L38-L69 With related bits for Fast tagging here:
https://github.com/digirati-co-uk/madoc-platform/blob/1.2.17/repos/auto-complete/src/Completion/Contributors/FastResourceCompletionContributor.php And wikidata here:
https://github.com/digirati-co-uk/madoc-platform/blob/1.2.17/repos/auto-complete/src/Completion/Contributors/WikiDataResourceCompletionContributor.php
=> NS-15 migration of completions from Madoc 1.x

services/madoc-ts/src/frontend/shared/utility/create-server-renderer.tsx
=> MAD-1152 changed to use local name if available

services/madoc-ts/src/app.ts, services/madoc-ts/src/config.ts, services/madoc-ts/src/frontend/admin/pages/system/system-status.tsx, services/madoc-ts/src/frontend/shared/plugins/external/server-renderer-for.ts, services/madoc-ts/src/frontend/shared/utility/create-server-renderer.tsx, services/madoc-ts/src/frontend/shared/utility/create-universal-component.ts, services/madoc-ts/src/frontend/site/pages/all-tasks.tsx, services/madoc-ts/src/frontend/site/pages/tasks/review-listing/review-listing-page.tsx, services/madoc-ts/src/gateway/api.ts, services/madoc-ts/src/middleware/slow-requests.ts, services/madoc-ts/src/routes/admin/pm2.ts, services/madoc-ts/src/routes/projects/get-project.ts, services/madoc-ts/src/utility/cache-helper.ts
This adds 3 features:
- Disables server-side rendering on the 2 review/task pages.
- Adds a Stale-while-revalidate memory cache and uses it for slow project queries
- Adds a new request trace and in-memory store of the slowest requests. (avg, max, count)
The request trace is visible on the System page in the admin.
It can be disabled with the environment variable flag: `DISABLE_SLOW_REQUEST_TRACKING=true`
=> Cache project

CHANGELOG.md, services/madoc-ts/src/frontend/site/blocks/EmbedItem.tsx, services/madoc-ts/translations/en/madoc.json
Now works with both youtube and awesomescreenshots
=> add allow same origin on embeded item
