README.md
bin/madoc
repos/iiif-storage/src/Job/ImportCanvases.php
repos/iiif-storage/view/iiif-storage/collection/list.twig

* Fixes Init command to not pull in older internal repositories
* Moved internal repository command to `madoc init-internal`
* Added login details to Readme.
* Fixed "All collections" page
* Guarded canvas imports, skips past errors when importing logging them.

Bug fixes December 2018

---

repos/iiif-storage/src/Job/ImportCanvases.php

- Added import warning when importing orphan canvases

Import changes and warnings

---

repos/public-user/src/Subscriber/AnnotationStatsSubscriber.php

Migrated away from using the old canvas_mapping_table instead just
looking for IIIF items in the CMS.
This is less tied to a specific implementation and could be used
stand alone if you were to create a resource class with the same
name (IIIF Canvas).

Fixed annotation stat subscriber

---

repos/iiif-storage/config/service.config.php
repos/iiif-storage/src/Aggregate/DereferencedCollection.php
repos/iiif-storage/src/Aggregate/DereferencedManifest.php
repos/iiif-storage/src/Aggregate/ScheduleEmbeddedCanvases.php
repos/iiif-storage/src/Aggregate/ScheduleEmbeddedManifests.php
repos/iiif-storage/src/Controller/ManifestController.php
repos/iiif-storage/src/Job/ImportCanvases.php
repos/iiif-storage/src/Job/ImportManifests.php
repos/iiif-storage/src/Listener/ImportContentListener.php
repos/iiif-storage/src/Utility/CheapOmekaRelationshipRequest.php
repos/shared-library/src/Model/ItemRequest.php

- Added unique collections and manifests importing, with manifests being reused in collections uploaded

Unique Resources

---

bin/madoc
database/sql/14-public-user.sql
repos/elucidate-proxy/src/Controller/ContainerController.php
repos/iiif-storage/Module.php
repos/iiif-storage/config/service.config.php
repos/iiif-storage/src/JsonBuilder/MetadataAggregator.php
repos/iiif-storage/src/Listener/TargetStatusUpdateListener.php
repos/iiif-storage/src/Repository/CanvasRepository.php
repos/iiif-storage/view/iiif-storage/partials/canvas-mark-as-complete.twig
repos/public-user/Module.php
repos/public-user/config/services.config.php
repos/public-user/src/Controller/AccountController.php
repos/public-user/src/Stats/AnnotationStatisticsService.php
repos/public-user/src/Stats/BookmarksService.php
repos/public-user/src/Stats/ContributorsService.php
repos/public-user/src/Subscriber/AnnotationStatsSubscriber.php

Some features from NLW migrated over:
* Track user bookmarks in table joining omeka resources
* When omeka item is annotated add "in progress" flag to omeka item
* When omeka item is marked as "complete", add flag to omeka item
This will allow us to drive quite a few more user interfaces not included in this PR:
* Listing user bookmarks (on page or in IIIF collection)
* Showing crowdsourcing progress on website
* Top contributors
* Latest annotated images (sort by modified date where item is in progress)
* Most bookmarked images
* Recently completed images
These will likely be page blocks that can be brought together on normal site pages, such as the homepage

Statistics

---

repos/annotation-studio/Module.php
repos/iiif-storage/config/service.config.php
repos/iiif-storage/src/Listener/TargetStatusUpdateListener.php
repos/iiif-storage/src/Media/CollectionSnippetRenderer.php
repos/public-user/Module.php
repos/public-user/src/Controller/LoginController.php
repos/public-user/view/public-user/login/register.twig

- Added ability to have static elucidate per site
- Fixed registration display (less fields)
- Fixed transcriber permissions when creating annotations
- Fixed original ids and annotations bugs

User and registration bugs

---

repos/annotation-studio/src/AnnotationStudio.php
repos/iiif-storage/src/Media/CrowdSourcingBannerIngester.php
repos/madoc-crowd-sourcing-theme/asset/css/style.css
repos/madoc-crowd-sourcing-theme/config/theme.ini
repos/madoc-crowd-sourcing-theme/view/layout/layout.phtml

Annotation studio update, logo updates to base theme to support title and logo, and quick fix to crowd sourcing banner collection id.

Theme updates

---

config/omeka-app/application.config.php
repos/elucidate/Module.php
repos/elucidate/config/services.config.php
repos/elucidate/src/Controller/FlaggingController.php
repos/elucidate/src/Subscriber/FlaggingNotificationSubscriber.php
repos/iiif-storage/view/iiif-storage/partials/canvas-flagging.twig
repos/public-user/config/module.config.php

- Allow non-registered users to flag items
- Allow non-administrators to flag items
- Fixed SMTP configuration
- Added fallback to sendmail
Requies sendmail to be added in latest Omeka container
Fixes #63

Flagging notifications

---

CHANGELOG.md
repos/madoc-crowd-sourcing-theme/view/layout/layout.phtml
repos/omeka-i18n-module/Module.php
repos/omeka-i18n-module/view/common/locale-helper.phtml

- Added configuration option to the site settings for official locales to be shown in a language switcher
- Added language switcher to the i18n module, available to be pulled into a theme

Language switcher

---

CHANGELOG.md
repos/iiif-storage/config/controllers.config.php
repos/iiif-storage/config/routes.config.php
repos/iiif-storage/config/service.config.php
repos/iiif-storage/src/Aggregate/AddImageService.php
repos/iiif-storage/src/Controller/AdminController.php
repos/iiif-storage/src/Job/ImportCanvases.php
repos/iiif-storage/src/Job/IngestCanvasThumbnail.php
repos/iiif-storage/src/Media/ManifestSnippetRenderer.php
repos/iiif-storage/src/Repository/CanvasRepository.php
repos/iiif-storage/src/Repository/ManifestRepository.php
repos/iiif-storage/view/iiif-storage/admin/canvas-admin.twig
repos/iiif-storage/view/iiif-storage/media/manifest-list.twig
repos/iiif-storage/view/iiif-storage/media/manifest-snippet-carousel.twig
repos/iiif-storage/view/iiif-storage/media/manifest-snippet.twig

Example UI
This is available at: `/admin/iiif/canvas/{id}` and the only action currently available is to request to re-request an image for thumbnails.
You can also POST directly to `/admin/iiif/canvas/{id}/ingest-thumbnail` if you wanted to batch some up.

Re-ingest image

---

repos/annotation-studio/config/services.config.php
repos/annotation-studio/src/Admin/ConfigurationForm.php
repos/annotation-studio/src/AnnotationStudio.php
repos/iiif-storage/asset/css/iiif-storage.css
repos/iiif-storage/view/iiif-storage/partials/canvas-thumbnail.twig
repos/public-user/Module.php
repos/public-user/src/Settings/PublicUserSettings.php
repos/public-user/src/Subscriber/AnnotationStatsSubscriber.php
repos/public-user/src/Subscriber/ManifestStatsSubscriber.php

* Changed the options presented for registering users when creating a site. Will not only allow `transcriber` role to be an option. This is the only user with locked down permissions.
* Fixed the google map API configuration in the backend - will now use the configured key and load in the google maps api with that key
* Fixed the progress dots shown when transcribing an image. Will show in progress, not started and completed on the canvas page and add css classes to them.

November bug fixes

---

services/madoc/packages/elucidate/config/services.config.php
services/madoc/packages/madoc-crowd-sourcing-theme/asset/css/style.css
services/madoc/packages/public-user/config/services.config.php
services/madoc/packages/public-user/src/Controller/AccountController.php
services/madoc/packages/public-user/src/Controller/AdminInvitationsController.php
services/madoc/packages/public-user/src/Controller/LoginController.php
services/madoc/packages/public-user/src/Controller/UserProfileController.php
services/madoc/packages/public-user/view/public-user/account/profile.twig
services/madoc/packages/shared-library/composer.json
services/madoc/packages/shared-library/src/Factory/GuzzleClientFactory.php

* List of sites on site profiles
* Added validation for admin
* Fixed bug with non-public sites and invitations

Additional validation of invitations

---

repos/auto-complete/config/services.config.php
repos/auto-complete/src/Completion/Contributors/WikiDataResourceCompletionContributor.php

Resource to pull in data from wikidata - https://www.wikidata.org/w/api.php?action=wbsearchentities&language=en&format=json&search=wales
endpoint - /api/complete?class=WikiData&q=wales

adding wiki data endpoint

---

services/madoc-ts/Dockerfile

https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images

Move away from alpine to fix segfault

---

services/madoc-ts/.gitignore
services/madoc-ts/src/frontend/admin/molecules/PreviewCollection.tsx
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/project-tasks.tsx
services/madoc-ts/src/frontend/admin/pages/tasks/collection-import-task.tsx
services/madoc-ts/src/frontend/admin/pages/tasks/manifest-import-task.tsx
services/madoc-ts/src/frontend/admin/pages/tasks/task-router.tsx
services/madoc-ts/src/frontend/shared/atoms/SnippetLarge.tsx
services/madoc-ts/src/frontend/shared/atoms/SubtaskProgress.tsx
services/madoc-ts/src/frontend/shared/atoms/TickIcon.tsx
services/madoc-ts/src/frontend/shared/components/CanvasSnippet.tsx
services/madoc-ts/src/frontend/shared/components/CollectionSnippet.tsx
services/madoc-ts/src/frontend/shared/components/ManifestSnippet.tsx
services/madoc-ts/src/frontend/shared/components/SubjectSnippet.tsx
services/madoc-ts/src/frontend/shared/utility/href-link.tsx
services/madoc-ts/src/gateway/tasks/import-canvas.ts
services/madoc-ts/stories/progress.stories.tsx
services/madoc-ts/stories/snippet.stories.tsx

Task subject snippets

---

services/madoc-ts/src/frontend/admin/molecules/MetadataListEditor.tsx
services/madoc-ts/src/frontend/admin/pages/content/manifests/edit-manifest-metadata.tsx
services/madoc-ts/src/utility/iiif-metadata.ts

Metadata improvements

---

services/madoc-ts/src/frontend/shared/atoms/ImageStrip.tsx
services/madoc-ts/src/frontend/shared/components/Pagination.tsx
services/madoc-ts/src/frontend/site/pages/view-collection.tsx
services/madoc-ts/src/frontend/site/pages/view-manifest.tsx

For the user facing manifests and collections.

MAD-128 Added grid variation

---

services/madoc-ts/src/frontend/admin/molecules/CollectionStructureEditor.tsx
services/madoc-ts/src/frontend/admin/molecules/MetadataListEditor.tsx
services/madoc-ts/src/frontend/admin/molecules/Pagination.tsx
services/madoc-ts/src/frontend/admin/molecules/PreviewCollection.tsx
services/madoc-ts/src/frontend/admin/molecules/PreviewManifest.tsx
services/madoc-ts/src/frontend/admin/pages/content/canvases/canvas.tsx
services/madoc-ts/src/frontend/admin/pages/content/collections/collection-list.tsx
services/madoc-ts/src/frontend/admin/pages/content/manifests/edit-manifest-structure.tsx
services/madoc-ts/src/frontend/admin/pages/content/manifests/manifest-list.tsx
services/madoc-ts/src/frontend/admin/pages/content/manifests/manifest-projects.tsx
services/madoc-ts/src/frontend/admin/pages/content/manifests/manifest.tsx
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/capture-models/capture-model-list.tsx
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/capture-models/capture-models.tsx
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/list-projects.tsx
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/project-content.tsx
services/madoc-ts/src/frontend/admin/pages/homepage.tsx
services/madoc-ts/src/frontend/admin/pages/tasks/collection-import-task.tsx
services/madoc-ts/src/frontend/admin/pages/tasks/manifest-import-task.tsx
services/madoc-ts/src/frontend/admin/routes.tsx
services/madoc-ts/src/frontend/shared/atoms/Button.tsx
services/madoc-ts/src/frontend/shared/atoms/ImageGrid.tsx
services/madoc-ts/src/frontend/shared/atoms/ImageStrip.tsx
services/madoc-ts/src/frontend/shared/atoms/IntlField.tsx
services/madoc-ts/src/frontend/shared/atoms/Statistics.tsx
services/madoc-ts/src/frontend/shared/atoms/Table.tsx
services/madoc-ts/src/frontend/shared/components/Pagination.tsx
services/madoc-ts/stories/atoms.stories.tsx
services/madoc-ts/stories/collection.stories.tsx

Miscellaneous frontend fixes arising from UX review. See https://docs.google.com/document/d/1J9p4INqonzgjbY6owS4FjjvlwbMzhdAUFiwN2xJg9LI/edit# for full details plus my comments describing what I've done

Frontend improvements from UX review

---

services/madoc-ts/__tests__/index.test.ts
services/madoc-ts/migrations/2020-08-19T18-51.linking-properties.sql
services/madoc-ts/migrations/down/2020-08-19T18-51.linking-properties.sql
services/madoc-ts/src/database/queries/linking-queries.ts
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/gateway/tasks/import-canvas.ts
services/madoc-ts/src/gateway/tasks/import-manifest.ts
services/madoc-ts/src/router.ts
services/madoc-ts/src/routes/iiif/canvases/create-canvas.ts
services/madoc-ts/src/routes/iiif/collections/create-collection.ts
services/madoc-ts/src/routes/iiif/linking/add-linking.ts
services/madoc-ts/src/routes/iiif/linking/delete-linking.ts
services/madoc-ts/src/routes/iiif/linking/get-linking.ts
services/madoc-ts/src/routes/iiif/linking/update-linking.ts
services/madoc-ts/src/routes/iiif/manifests/create-manifest.ts
services/madoc-ts/src/utility/extract-links.ts
services/madoc-ts/src/utility/iiif-get-label.ts
services/madoc-ts/src/utility/postgres-tags.ts

* Example response for Wellcome manifest: https://paw.pt/fkMF9O08
* Example response for Wellcome canvas: https://paw.pt/fkMGKWGx
* Creating a custom link on a resource (performs upsert): https://paw.pt/fkMG2Cfd
* Minimum viable link: https://paw.pt/fkMGSP9v
There is no UI yet for managing these in Madoc.

Linking properties

---

docker-compose.yml
services/madoc-ts/src/frontend/shared/atoms/CanvasStatus.tsx
services/madoc-ts/src/frontend/shared/atoms/Images.tsx
services/madoc-ts/src/frontend/site/pages/loaders/manifest-loader.tsx
services/madoc-ts/src/frontend/site/pages/view-manifest.tsx
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/router.ts
services/madoc-ts/src/routes/projects/get-project-task.ts
services/madoc-ts/src/routes/projects/get-project.ts
services/madoc-ts/src/routes/site/site-manifest.ts
services/madoc-ts/src/types/schemas/manifest-full.ts
services/madoc-ts/src/utility/parse-project-id.ts
services/tasks-api/src/database/get-task.ts
services/tasks-api/src/router.ts
services/tasks-api/src/routes/get-single-task.ts
services/tasks-api/src/routes/get-subject-statistics.ts

MAD-346 canvas status

---

services/madoc-ts/src/database/queries/count-queries.ts
services/madoc-ts/src/database/queries/get-collection-snippets.ts
services/madoc-ts/src/database/queries/get-manifest-snippets.ts
services/madoc-ts/src/frontend/site/pages/loaders/manifest-loader.tsx
services/madoc-ts/src/frontend/site/pages/view-manifest.tsx
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/routes/iiif/collections/get-collection.ts
services/madoc-ts/src/routes/iiif/manifests/get-manifest.ts
services/madoc-ts/src/routes/site/site-manifest.ts
services/tasks-api/src/routes/get-subject-statistics.ts

Contains 2 things:
* General filtering for site manifests and collections based on project status
* UI element to hide completed canvases on manifest page

MAD-160 Filter status

---

configuration/defaults/madoc.json
services/madoc-ts/src/frontend/shared/atoms/Images.tsx
services/madoc-ts/src/frontend/site/pages/loaders/collection-loader.tsx
services/madoc-ts/src/frontend/site/pages/tasks/crowdsourcing-task.tsx
services/madoc-ts/src/frontend/site/pages/view-canvas-model.tsx
services/madoc-ts/src/frontend/site/pages/view-canvas.tsx
services/madoc-ts/src/frontend/site/pages/view-collection.tsx
services/madoc-ts/src/frontend/site/pages/view-manifest.tsx
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/gateway/tasks/crowdsourcing-canvas-task.ts
services/madoc-ts/src/gateway/tasks/crowdsourcing-manifest-task.ts
services/madoc-ts/src/gateway/tasks/crowdsourcing-task.ts
services/madoc-ts/src/queue/producer.ts
services/madoc-ts/src/routes/projects/create-resource-claim.ts
services/madoc-ts/src/routes/projects/get-project.ts
services/madoc-ts/src/routes/site/site-canvas-tasks.ts
services/madoc-ts/src/routes/site/site-collection.ts
services/madoc-ts/src/routes/site/site-manifest.ts
services/madoc-ts/src/types/schemas/collection-full.ts
services/madoc-ts/src/types/schemas/config-response.ts
services/madoc-ts/src/types/schemas/project-configuration.ts
services/madoc-ts/src/types/tasks/crowdsourcing-collection-task.ts
services/madoc-ts/src/types/tasks/crowdsourcing-manifest-task.ts
services/madoc-ts/src/types/tasks/crowdsourcing-task.ts

MAD-238 Setting max contributions

---

services/madoc-ts/src/types/search.ts

Update types to contexts instead of context

update context to contexts

---

services/madoc-ts/src/frontend/admin/pages/homepage.tsx
services/madoc-ts/src/frontend/shared/atoms/Grid.tsx
services/madoc-ts/src/frontend/shared/atoms/Kanban.tsx
services/madoc-ts/src/frontend/shared/hooks/use-contributor-tasks.ts
services/madoc-ts/src/frontend/shared/hooks/use-reviewer-tasks.ts
services/madoc-ts/src/frontend/site/components.tsx
services/madoc-ts/src/frontend/site/pages/tasks/crowdsourcing-multi-review.tsx
services/madoc-ts/src/frontend/site/pages/user-homepage.tsx
services/madoc-ts/src/frontend/site/pages/view-project.tsx
services/madoc-ts/src/frontend/site/pages/view-user.tsx
services/madoc-ts/src/frontend/site/routes.ts
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/router.ts
services/madoc-ts/src/routes/user/get-user.ts
services/madoc-ts/src/types/omeka/User.ts
services/madoc-ts/src/utility/parse-urn.ts
services/tasks-api/src/routes/get-all-tasks.ts

Users on the task page are now clickable - taking you to a simple user page.

User page + task links

---

services/madoc-ts/src/frontend/shared/components/SearchFacets.tsx
services/madoc-ts/src/frontend/shared/components/SearchResults.tsx
services/madoc-ts/src/frontend/site/pages/search.tsx

This PR: 
Retains the search facets if the page is reloaded. 
Adds a maximum width to the facet labels.
Shortens the search hint to "Keyword search" per Ville's request

Facets styling

---

CHANGELOG.md
repos/annotation-studio/Module.php
repos/annotation-studio/config/routes.config.php
repos/annotation-studio/src/AnnotationStudioFactory.php
repos/annotation-studio/src/CaptureModel/Router.php
repos/annotation-studio/src/Components/CorePlugin.php
repos/annotation-studio/src/Controller/CaptureModelController.php
repos/capture-model-import/view/capture-model-import/capture-model-import/export.twig
repos/elucidate/view/elucidate/activity/canvas-activity.twig
repos/elucidate/view/elucidate/activity/user-activity.twig
repos/elucidate/view/elucidate/item/view.twig
repos/iiif-storage/view/iiif-storage/admin/canvas-admin.twig
repos/iiif-storage/view/iiif-storage/canvas/view-image.twig
repos/iiif-storage/view/iiif-storage/collection/list.twig
repos/iiif-storage/view/iiif-storage/collection/view.twig
repos/iiif-storage/view/iiif-storage/media/crowd-sourcing-banner.twig
repos/iiif-storage/view/iiif-storage/media/latest-annotated-images.twig
repos/iiif-storage/view/iiif-storage/media/top-contributors.twig
repos/iiif-storage/view/iiif-storage/partials/pagination.twig
repos/omeka-i18n-module/src/Site/LocalizationListener.php
repos/omeka-i18n-module/src/Translator/ContextualTranslator.php
repos/public-user/view/public-user/public-profile/view-profile.twig
repos/search/view/madoc-search/media/annotation-statistics.twig

* Adds various missing translations
* Fixes navigation translations

Translation fixes

---

services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/project-metadata.tsx
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/project-model-editor.tsx

Switches Changed saved with changes saved

---

services/madoc-ts/src/frontend/admin/molecules/CollectionStructureEditor.tsx
services/madoc-ts/src/frontend/admin/pages/content/collections/collection-list.tsx
services/madoc-ts/src/frontend/admin/pages/content/collections/create-collection.tsx
services/madoc-ts/src/frontend/admin/pages/homepage.tsx
services/madoc/packages/public-user/src/Controller/AdminInvitationsController.php

Opted for an additional tab on the manage manifests interface

Adds delete a manifest option.

---

services/madoc-ts/src/frontend/site/pages/view-collection.tsx

Scope search to searching within a collection, when you click search this collection on collection view

Add in search this collection

---

services/madoc-ts/package.json
services/madoc-ts/src/frontend/shared/components/SimpleAtlasViewer.tsx
services/madoc-ts/src/frontend/site/pages/user-homepage.tsx
services/madoc-ts/yarn.lock

MAD-530 zoom controls

---

services/madoc-ts/package.json
services/madoc-ts/src/frontend/admin/pages/content/canvases/canvas-plaintext.tsx
services/madoc-ts/src/frontend/admin/pages/content/canvases/canvas-search-index.tsx
services/madoc-ts/src/frontend/shared/components/NotFoundPage.tsx
services/madoc-ts/yarn.lock

MAD-549 Added better handling of error boundary

---

services/madoc-ts/src/frontend/admin/index.tsx
services/madoc-ts/src/frontend/admin/molecules/AdminHeader.tsx
services/madoc-ts/src/frontend/admin/molecules/AdminSidebar.tsx
services/madoc-ts/src/frontend/shared/atoms/AdminPageTitle.tsx
services/madoc-ts/src/frontend/shared/atoms/Breadcrumbs.tsx
services/madoc-ts/src/frontend/shared/components/AdminMenu.tsx
services/madoc-ts/stories/admin.stories.tsx

Added admin sidebar

---

services/madoc-ts/src/frontend/shared/atoms/SnippetLarge.tsx

Fixed styling of snippet

---

services/madoc-ts/package.json
services/madoc-ts/src/frontend/admin/molecules/ViewContentFetch.tsx
services/madoc-ts/src/frontend/shared/atoms/SmallToast.tsx
services/madoc-ts/src/frontend/shared/caputre-models/new/EditorContent.tsx
services/madoc-ts/src/frontend/shared/components/ViewContent.tsx
services/madoc-ts/src/frontend/shared/components/ViewExternalContent.tsx
services/madoc-ts/src/frontend/site/features/CanvasSimpleEditor.tsx
services/madoc-ts/translations/en/madoc.json
services/madoc-ts/yarn.lock

MAD-738 MAD-741

---

services/madoc-ts/__tests__/routes/create-resource-claim.test.ts
services/madoc-ts/src/gateway/tasks/crowdsourcing-task.ts
services/madoc-ts/src/routes/projects/create-resource-claim.ts

* Status 3 -> 2 for manifest in review
* Prevent manifests automatically being completed in current workflows

Small task fixes

---

services/madoc-ts/src/frontend/shared/atoms/Button.tsx

MAD-856: Rounded button disabled state styling

---

docker-compose.yml
services/madoc-ts/src/extensions/page-blocks/block-editor-react.ts
services/madoc-ts/src/extensions/page-blocks/extension.ts
services/madoc-ts/src/extensions/projects/types.ts
services/madoc-ts/src/extensions/registry-extension.ts
services/madoc-ts/src/frontend/shared/atoms/AddBlock.tsx
services/madoc-ts/src/frontend/shared/atoms/ContextualMenu.tsx
services/madoc-ts/src/frontend/shared/atoms/Heading1.tsx
services/madoc-ts/src/frontend/shared/atoms/Heading2.tsx
services/madoc-ts/src/frontend/shared/components/CrowdSourcingBanner.tsx
services/madoc-ts/src/frontend/shared/page-blocks/block-creator.tsx
services/madoc-ts/src/frontend/shared/page-blocks/render-blank-slot.tsx
services/madoc-ts/src/frontend/shared/page-blocks/slot-editor.tsx
services/madoc-ts/src/frontend/shared/plugins/external/block-config-for.ts
services/madoc-ts/src/frontend/shared/plugins/plugin-manager.ts
services/madoc-ts/stories/page-blocks.stories.tsx

MAD-877 - empty slot UI + block lists

---

services/madoc-ts/src/frontend/shared/components/SearchResults.tsx
services/madoc-ts/src/frontend/site/components.tsx
services/madoc-ts/src/frontend/site/features/ProjectActions.tsx
services/madoc-ts/src/frontend/site/pages/view-project-notes.tsx
services/madoc-ts/src/frontend/site/routes.ts
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/router.ts
services/madoc-ts/src/routes/projects/get-all-project-notes.ts
services/madoc-ts/src/types/personal-notes.ts
services/madoc-ts/translations/en/madoc.json

MAD-910 listing personal notes

---

services/madoc-ts/package.json
services/madoc-ts/src/frontend/shared/caputre-models/EntityInstance.tsx
services/madoc-ts/src/frontend/shared/caputre-models/VerboseSelector.tsx
services/madoc-ts/yarn.lock

Depends on https://github.com/digirati-co-uk/capture-models/pull/41

MAD-749: Show preview and delete options for entity selectors

---

CHANGELOG.md
services/madoc-ts/src/extensions/capture-models/DynamicDataSources/DynamicDataSources.extension.ts
services/madoc-ts/src/extensions/capture-models/Paragraphs/Paragraphs.extension.ts
services/madoc-ts/src/extensions/capture-models/crowdsourcing-api.ts
services/madoc-ts/src/frontend/shared/hooks/use-loaded-capture-model.ts
services/madoc-ts/src/frontend/shared/plugins/use-module.ts
services/madoc-ts/src/frontend/site/hooks/use-crowdsourcing-task-details.ts
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/utility/parse-model-target.ts
services/madoc-ts/src/utility/resolve-urn.ts

Small internal refactor - no public API changes.

Added new "api.crowdsourcing" namespace 

---

CHANGELOG.md
docker-compose.yml
services/madoc-ts/src/frontend/shared/atoms/Images.tsx
services/madoc-ts/src/frontend/shared/caputre-models/inspector/ViewDocument.tsx
services/madoc-ts/src/frontend/shared/components/RevisionList.tsx
services/madoc-ts/src/frontend/shared/utility/query-config.ts
services/madoc-ts/src/frontend/site/features/CanvasModelCompleteMessage.tsx
services/madoc-ts/src/frontend/site/features/CanvasModelReadOnlyViewer.tsx
services/madoc-ts/src/frontend/site/features/HighlightedCanvasSearchResults.tsx
services/madoc-ts/src/frontend/site/hooks/canvas-menu/annotation-panel.tsx
services/madoc-ts/src/frontend/site/hooks/canvas-menu/document-panel.tsx
services/madoc-ts/src/frontend/site/hooks/canvas-menu/personal-notes.tsx
services/madoc-ts/src/frontend/site/pages/view-canvas.tsx

- Fixed bug where "No document exists" would appear multiple times in the sidebar
- Fixed bug where logged-out user would make requests to personal notes (with a 401)
- Fixed missing annotations on model page
- Fixed message "Maximum number of contributors reached" for logged-out user
- Fixed bug where short submissions would appear collapsed in sidebar
- Fixed re-fetching on window focus
- Fixed bug where draft annotations could be seen

Various fixes for viewing annotation output

---

services/madoc-ts/src/routes/site/site-search.ts

performance regression
TODO: Changelog

Fixed searching by type

---

CHANGELOG.md
services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultPostSubmission.tsx
services/madoc-ts/src/frontend/shared/capture-models/new/components/EditorSlots.tsx
services/madoc-ts/src/frontend/shared/configuration/site-config.ts
services/madoc-ts/src/frontend/site/features/CanvasSimpleEditor.tsx
services/madoc-ts/src/types/schemas/project-configuration.ts
services/madoc-ts/translations/cy/madoc.json
services/madoc-ts/translations/en/madoc.json
services/madoc-ts/translations/nl/madoc.json

* Only works when preview is also disabled for now

MAD-1098 Added configuration to hide "next canvas" 

---

services/madoc-ts/__tests__/capture-models/helpers/capture-model-shorthand-test.test.ts
services/madoc-ts/__tests__/utility/templated-value-format.test.ts
services/madoc-ts/package.json
services/madoc-ts/src/extensions/projects/extension.ts
services/madoc-ts/src/extensions/projects/templates/metadata-suggestions.tsx
services/madoc-ts/src/extensions/projects/types.ts
services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/new-project-from-template.tsx
services/madoc-ts/src/frontend/shared/capture-models/EditorShorthandCaptureModel.tsx
services/madoc-ts/src/frontend/shared/capture-models/helpers/capture-model-shorthand-text.ts
services/madoc-ts/src/frontend/shared/capture-models/new/components/DefaultManagePropertiesList.tsx
services/madoc-ts/src/frontend/shared/utility/templated-value-format.ts
services/madoc-ts/src/routes/projects/create-new-project.ts
services/madoc-ts/src/types/schemas/create-project.ts
services/madoc-ts/stories/capture-models/example-models.stories.tsx
services/madoc-ts/test-utility/unindent.ts
services/madoc-ts/yarn.lock

This is a project template to edit metadata. It does not contain the runtime functions, or any export options for adding to the database or search yet.

MAD-1116 Metadata capture model

---

CHANGELOG.md
services/madoc-ts/src/frontend/shared/atoms/TimeAgo.tsx

MAD-1230 Time ago format improvement

---

CHANGELOG.md
services/madoc-ts/src/frontend/site/hooks/canvas-menu/document-panel.tsx
services/madoc-ts/src/frontend/site/pages/tasks/preview-crowdsourcing-task.tsx
services/madoc-ts/translations/en/madoc.json

Match logic in `/document-panel.tsx` for showing notification as `Viewdocument.tsx` uses to show approved submisions

change validModels to filter non approved and empty fields

---

docker-compose.enrichment.yml
docker-compose.yml
services/madoc-ts/src/extensions/enrichment/authority/types.ts
services/madoc-ts/src/frontend/site/features/TopicHero.tsx
services/madoc-ts/src/frontend/site/features/TopicTypeHero.tsx
services/madoc-ts/src/frontend/site/pages/view-topic-type.tsx
services/madoc-ts/src/frontend/site/pages/view-topic.tsx
services/madoc-ts/src/routes/site/site-topic.ts
services/madoc-ts/src/types/schemas/topics.ts

Ida 927/hero content curation

---

services/madoc-ts/src/extensions/enrichment/authority/authority-extension.ts
services/madoc-ts/src/extensions/enrichment/extension.ts
services/madoc-ts/src/frontend/site/features/AddTagButton.tsx
services/madoc-ts/src/frontend/site/features/AddTopicButton.tsx
services/madoc-ts/src/frontend/site/features/SearchPageFilters.tsx
services/madoc-ts/src/frontend/site/features/TaggingFormPannel.tsx
services/madoc-ts/src/frontend/site/features/TopicGrid.tsx
services/madoc-ts/src/frontend/site/pages/loaders/topic-type-loader.tsx
services/madoc-ts/src/routes/site/site-topic-type.ts

Add new tag from chosen type

---

services/madoc-ts/src/frontend/admin/pages/crowdsourcing/projects/project-configuration.tsx
services/madoc-ts/src/routes/site/site-configuration.ts
services/madoc-ts/src/types/schemas/project-configuration.ts

Added project sources

---

services/madoc-ts/src/frontend/shared/capture-models/_components/ViewDocument/ViewDocument.styles.ts
services/madoc-ts/src/frontend/shared/capture-models/editor/input-types/TextField/TextField.preview.tsx

wrap multi annotations and add some spacing and min with on pre-wraped lables

Annotation lables wrapped for multi

---

CHANGELOG.md
services/madoc-ts/src/frontend/admin/pages/content/page-blocks/list-pages.tsx
services/madoc-ts/src/frontend/shared/components/PageCreator.tsx
services/madoc-ts/src/frontend/shared/page-blocks/block-language-editor.tsx
services/madoc-ts/src/frontend/shared/page-blocks/render-slot.tsx
services/madoc-ts/src/frontend/shared/page-blocks/slot-editor.tsx
services/madoc-ts/src/frontend/shared/page-blocks/sort-site-blocks.ts

NS-32 - Multi-lingual page blocks

---

services/madoc-ts/src/frontend/admin/pages/system/system-status.tsx
services/madoc-ts/src/frontend/site/pages/view-project.tsx
services/madoc-ts/src/frontend/tailwind/components/slot-tabs.tsx
services/madoc-ts/src/gateway/api.ts
services/madoc-ts/src/gateway/tasks/crowdsourcing-review.ts
services/madoc-ts/src/gateway/tasks/crowdsourcing-task.ts
services/madoc-ts/src/repository/project-repository.ts
services/madoc-ts/src/router.ts
services/madoc-ts/src/routes/projects/create-new-project.ts
services/madoc-ts/src/routes/projects/project-members.ts

* Adds user when crowdsourcing task is approved (contributor)
* Adds user when review task is complete (reviewer)
* Adds user when project is created
* Adds button to back-fill contributors (but not reviewers)
> [!NOTE]
> Migration requires latest Task API version

Project members

---

services/madoc-ts/schemas/ProjectConfiguration.json
services/madoc-ts/schemas/ProjectConfigurationNEW.json
services/madoc-ts/src/frontend/shared/layout/MaximiseWindow.tsx
services/madoc-ts/src/frontend/shared/layout/Modal.tsx
services/madoc-ts/src/frontend/site/pages/tasks/review-listing/ReviewNagivation.tsx
services/madoc-ts/src/frontend/site/pages/tasks/review-listing/review-listing-page.tsx
services/madoc-ts/src/frontend/site/pages/tasks/review-listing/single-review.tsx
services/madoc-ts/src/frontend/site/pages/view-project.tsx

move reviewNavigation to review-header 
fix text overflow for sub label 
fix canvas buttons on focus mode not showing

Review Dash bug fixes

---

services/madoc-ts/src/extensions/project-export/export-configs/canvas/canvas-model-export.ts
services/madoc-ts/src/extensions/project-export/export-configs/project/project-csv-simple-export.ts
services/madoc-ts/src/routes/site/site-published-models.ts

Added to:
- Project CSV export
- Canvas model export

Added ability to configure exports to include reviews
